/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppAppRouteRouteImport } from './routes/_app/app/route'
import { Route as AppAppIndexRouteImport } from './routes/_app/app/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as AppAppTrashRouteImport } from './routes/_app/app/trash'
import { Route as AppAppSettingsRouteImport } from './routes/_app/app/settings'
import { Route as AppAppNewRouteImport } from './routes/_app/app/new'
import { Route as AppAppNoteIdRouteImport } from './routes/_app/app/$noteId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/_auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/_auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppRouteRoute = AppAppRouteRouteImport.update({
  id: '/_app/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAppTrashRoute = AppAppTrashRouteImport.update({
  id: '/trash',
  path: '/trash',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppSettingsRoute = AppAppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppNewRoute = AppAppNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAppRouteRoute,
} as any)
const AppAppNoteIdRoute = AppAppNoteIdRouteImport.update({
  id: '/$noteId',
  path: '/$noteId',
  getParentRoute: () => AppAppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppAppRouteRouteWithChildren
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/app/$noteId': typeof AppAppNoteIdRoute
  '/app/new': typeof AppAppNewRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/trash': typeof AppAppTrashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/app/$noteId': typeof AppAppNoteIdRoute
  '/app/new': typeof AppAppNewRoute
  '/app/settings': typeof AppAppSettingsRoute
  '/app/trash': typeof AppAppTrashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app/app': typeof AppAppRouteRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_app/app/$noteId': typeof AppAppNoteIdRoute
  '/_app/app/new': typeof AppAppNewRoute
  '/_app/app/settings': typeof AppAppSettingsRoute
  '/_app/app/trash': typeof AppAppTrashRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/_app/app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/register'
    | '/app/$noteId'
    | '/app/new'
    | '/app/settings'
    | '/app/trash'
    | '/api/auth/$'
    | '/app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/app/$noteId'
    | '/app/new'
    | '/app/settings'
    | '/app/trash'
    | '/api/auth/$'
    | '/app'
  id:
    | '__root__'
    | '/'
    | '/_app/app'
    | '/_auth/login'
    | '/_auth/register'
    | '/_app/app/$noteId'
    | '/_app/app/new'
    | '/_app/app/settings'
    | '/_app/app/trash'
    | '/api/auth/$'
    | '/_app/app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppAppRouteRoute: typeof AppAppRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app': {
      id: '/_app/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppAppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/': {
      id: '/_app/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/app/trash': {
      id: '/_app/app/trash'
      path: '/trash'
      fullPath: '/app/trash'
      preLoaderRoute: typeof AppAppTrashRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/settings': {
      id: '/_app/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppAppSettingsRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/new': {
      id: '/_app/app/new'
      path: '/new'
      fullPath: '/app/new'
      preLoaderRoute: typeof AppAppNewRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
    '/_app/app/$noteId': {
      id: '/_app/app/$noteId'
      path: '/$noteId'
      fullPath: '/app/$noteId'
      preLoaderRoute: typeof AppAppNoteIdRouteImport
      parentRoute: typeof AppAppRouteRoute
    }
  }
}

interface AppAppRouteRouteChildren {
  AppAppNoteIdRoute: typeof AppAppNoteIdRoute
  AppAppNewRoute: typeof AppAppNewRoute
  AppAppSettingsRoute: typeof AppAppSettingsRoute
  AppAppTrashRoute: typeof AppAppTrashRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteRouteChildren: AppAppRouteRouteChildren = {
  AppAppNoteIdRoute: AppAppNoteIdRoute,
  AppAppNewRoute: AppAppNewRoute,
  AppAppSettingsRoute: AppAppSettingsRoute,
  AppAppTrashRoute: AppAppTrashRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteRouteWithChildren = AppAppRouteRoute._addFileChildren(
  AppAppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppAppRouteRoute: AppAppRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
