name: "Deploy"

on:
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install deps
        run: npm ci

      - name: Run Biome Check
        run: npx biome check --write --unsafe

      - name: Build app
        run: npm run build

      - name: SSH to server and run script
          uses: appleboy/ssh-action@v1
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USERNAME }}
            key: ${{ secrets.SSH_PRIVATE_KEY }}
            port: ${{ secrets.PORT }}
            script: whoami